# Main file, shared between all environments.

version: "3"

services:

  db:
    build: ./images/drupal-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  #phpcache:
  #  build: ./images/redis

  #search:
  #  image: guywithnose/solr:3.6.2

  php:
    build: ./images/platformsh-php71
    environment:
      DB_HOST: db
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_DRIVER: mysql
      CACHE_HOST: phpcache
      SEARCH_HOST: search
      BASE_DOMAIN: ${BASE_DOMAIN}
      PRIMARY_DOMAIN: ${PRIMARY_DOMAIN}
      PHP_IDE_CONFIG: "serverName=${PRIMARY_DOMAIN}.${BASE_DOMAIN}"
      ENVIRONMENT: ${ENVIRONMENT}

  web:
    image: tbfisher/drupal-web:nginx-1.8-dev-1
    environment:
      WEB_DOCROOT: /var/www/_www
      WEB_PHPFPM: "php:9000"

  webproxy:
    build:
      context: ./images/varnish
