# Development proxy for routing, SSL term.

version: '3'

services:

  search:
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.search.entrypoints=web"
      - 'traefik.http.routers.search.rule=Host(`search.${LDEV_BASE_DOMAIN}`)'
      - 'traefik.http.services.search.loadbalancer.server.port=8983'

  php:
    links:
      - 'proxy:${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'
      - 'proxy:www.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'
      - 'search:search.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'

  webproxy:
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.webproxy.entrypoints=web"
      - 'traefik.http.routers.webproxy.rule=HostRegexp(`${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}`, `{subdomain:[a-z0-9]+}.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}`)'
      - "traefik.http.routers.webproxysecure.entrypoints=websecure"
      - 'traefik.http.routers.webproxysecure.rule=HostRegexp(`${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}`, `{subdomain:[a-z0-9]+}.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}`)'
      - 'traefik.http.routers.webproxysecure.tls=true'

  mail:
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.mail.entrypoints=web"
      - 'traefik.http.routers.mail.rule=Host(`mail.${LDEV_BASE_DOMAIN}`)'
      - 'traefik.http.services.mail.loadbalancer.server.port=8025'

  proxy:
    image: traefik:v2.0
    container_name: proxy
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
