# Development environment.
# - Exposes ports.
# - Declares expendable volumes.
# - Maps code to local files.
# - Dev-only services.

version: "3"

services:

  db:
    ports:
      - '3306'
    volumes:
      - "db_data:/var/lib/mysql"

  phpcache:
    sysctls:
      net.core.somaxconn: 65535
    ports:
      - '6379'

  search:
    ports:
      - '8983'
    volumes:
      - "./code/example8/web/modules/contrib/search_api_solr/solr-conf/3.x:/opt/drupal/conf:ro"

  php:
    environment:
      PHP_IDE_CONFIG: "serverName=${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}"
    ports:
      - '9000'
    volumes:
      - "./code/example8:/var/www/web:cached"
      - "files_public:/var/www_files/public:rw"
      - "files_private:/var/www_files/private:rw"

  web:
    ports:
      - '80'
    volumes:
      - "./code/example8:/var/www/web:cached"
      - "files_public:/var/www_files/public:rw"
      - "files_private:/var/www_files/private:rw"

  mail:
    image: mailhog/mailhog
    ports:
      - '8025'
      - '25'

volumes:
  db_data:
    driver: local
  files_public:
    driver: local
  files_private:
    driver: local
