# Main file, shared between all environments.

version: "3"

services:

  db:
    build: ./images/pantheon-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  phpcache:
    build: ./images/redis

  search:
    image: guywithnose/solr:3.6.2

  php:
    build: ./images/pantheon-php72
    environment:
      DB_HOST: db
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_DRIVER: mysql
      CACHE_HOST: phpcache
      SEARCH_HOST: search
      BASE_DOMAIN: ${BASE_DOMAIN}
      PRIMARY_DOMAIN: ${PRIMARY_DOMAIN}
      ENVIRONMENT: ${ENVIRONMENT}

  web:
    image: tbfisher/drupal-web:nginx-1.8-dev-1
    environment:
      WEB_DOCROOT: /var/www/web
      WEB_PHPFPM: "php:9000"
    depends_on:
      - php
