# Development proxy for routing, SSL term.

version: '3'

services:

  search:
    labels:
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:search.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'
      - 'traefik.frontend.entryPoints=http'

  php:
    links:
      - 'proxy:${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'
      - 'proxy:www.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'
      - 'search:search.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'

  webproxy:
    labels:
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:www.${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN},${LDEV_PRIMARY_DOMAIN}.${LDEV_BASE_DOMAIN}'
      - 'traefik.frontend.entryPoints=http,https'

  mail:
    labels:
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mail.${LDEV_BASE_DOMAIN}'
      - 'traefik.frontend.entryPoints=http'

  proxy:
    image: traefik:1.7
    container_name: proxy
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    command: |
      -c /dev/null \
      --api \
      --docker \
      --logLevel=DEBUG \
      --accessLog \
      --entryPoints="Name:https Address::443 TLS:/certs/ssl-cert-snakeoil.crt,/certs/ssl-cert-snakeoil.key" \
      --entryPoints="Name:http Address::80"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './conf/traefik/certs:/certs'
