# Main file, shared between all environments.

version: "3"

services:

  db:
    build: ./images/drupal-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  #phpcache:
  #  image: sylvainlasnier/memcached

  #search:
  #  image: guywithnose/solr:3.6.2

  php:
    image: tbfisher/drupal-php:7.2-dev-5
    environment:
      DB_HOST: db
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_DRIVER: mysql
      CACHE_HOST: phpcache
      SEARCH_HOST: search
      BASE_DOMAIN: ${BASE_DOMAIN}
      PRIMARY_DOMAIN: ${PRIMARY_DOMAIN}
      ENVIRONMENT: ${ENVIRONMENT}

  web:
    image: tbfisher/drupal-web:httpd-2.4
    environment:
      WEB_DOCROOT: /var/www/web
      WEB_PHPFPM: "php:9000"
    depends_on:
      - php

  webproxy:
    build:
      context: ./images/varnish
    environment:
      VARNISH_VCL_DEFAULT_BACKEND_HOST: '"web"'
      VARNISH_VCL_DEFAULT_BACKEND_PORT: '"80"'
      VARNISH_VCL_DEFAULT_ACL_PURGE_BAN: '"php"'
    depends_on:
      - web
