# Main file, shared between all environments.

version: "3"

services:

  db:
    build: ./images/drupal-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${LDEV_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${LDEV_DATABASE_NAME}
      MYSQL_USER: ${LDEV_DATABASE_USER}
      MYSQL_PASSWORD: ${LDEV_DATABASE_PASSWORD}

  phpcache:
    build: ./images/redis

  search:
    image: solr:8
    # https://github.com/docker-solr/docker-solr#using-docker-compose
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - /opt/drupal

  php:
    image: tbfisher/drupal-php:7.3-dev-5
    environment:
      DB_HOST: db
      DB_USER: ${LDEV_DATABASE_USER}
      DB_PASSWORD: ${LDEV_DATABASE_PASSWORD}
      DB_NAME: ${LDEV_DATABASE_NAME}
      DB_DRIVER: mysql
      CACHE_HOST: phpcache
      SEARCH_HOST: search
      BASE_DOMAIN: ${LDEV_BASE_DOMAIN}
      PRIMARY_DOMAIN: ${LDEV_PRIMARY_DOMAIN}
      ENVIRONMENT: ${LDEV_ENVIRONMENT}

  web:
    image: tbfisher/drupal-web:nginx-1.16-dev-1
    environment:
      WEB_DOCROOT: /var/www/web
      WEB_PHPFPM: "php:9000"
    depends_on:
      - php

  webproxy:
    build:
      context: ./images/varnish
    environment:
      VARNISH_VCL_DEFAULT_BACKEND_HOST: '"web"'
      VARNISH_VCL_DEFAULT_BACKEND_PORT: '"80"'
      VARNISH_VCL_DEFAULT_ACL_PURGE_BAN: '"php"'
    depends_on:
      - web
