#!/usr/bin/env bash

# exit on error, unset vars
set -eu
# exit early for errors in pipelines
set -o pipefail

# Gets the directory containing this file.
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck source=inc/util.sh
source "$script_dir/inc/util.sh"

# current directory
pwd_dir=$(pwd)

# shell window dims for fitting container output to host.
if [ -z "${COLUMNS+x}" ]; then
    export COLUMNS=80
fi
if [ -z "${LINES+x}" ]; then
    export LINES=32
fi

# Include ldev env.
if [ -z "${LDEV_ENV_SCRIPT+x}" ]; then
    LDEV_ENV_SCRIPT="$script_dir/env"
fi
# shellcheck source=env
source "$LDEV_ENV_SCRIPT"

default_host_ip="$(docker::host-ip)"

usage() {
    cat << EOF
usage: $0 [options] [command] [container] [host-ip]

Enable/disable Xdebug.

ARGUMENTS:
    command   One of "en" to enable, or "dis" to disable, defaults to "en".
    container The php container to enable xdebug in, defaults to "$LDEV_PHP_CONTAINER".
    host-ip   Host ip address (for Xdebug to connect to), defaults to "$default_host_ip".

OPTIONS:
    -a        Enable xdebug.remote_autostart
              see https://xdebug.org/docs/remote#remote_autostart
    -v        Verbose output, prints every command to stdout.
    -h        Prints this help message.
EOF
    echo
}

# parse options
remote_autostart=0
while getopts ":avh" OPTION
do
    case $OPTION in
        a)
            remote_autostart=1
            ;;
        v)
            set -x
            ;;
        h)
            usage
            exit
            ;;
        \?)
            util::echo error "Invalid option: -$OPTARG" >&2
            usage
            exit 1
            ;;
        :)
            util::echo error "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

# parse arguments
shift "$((OPTIND-1))"
# if $1 is unbound
if [ -z "${1+x}" ]; then
    cmd=en
else
    case "$1" in
        en)
            cmd='en'
            ;;
        dis)
            cmd='dis'
            ;;
        :)
            util::echo error "Argument command \"$1\" not one of \"en\" or \"dis\"." >&2
            usage
            exit 1
            ;;
    esac
fi
if [ -z "${2+x}" ]; then
    php_container=$LDEV_PHP_CONTAINER
else
    php_container=$2
fi
if [ -z "${3+x}" ]; then
    host_ip=$default_host_ip
else
    host_ip=$3
fi

# for docker cmds
cd "$LDEV_PROJ_DIR"

main() {
    # container path to ini to write to
    ini_path=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    # grab zend_extension=path/to/xdebug.so line (changes per php build)
    zend_extension=$(docker-compose exec "$php_container" /bin/bash -c "cat '$ini_path' | grep -m 1 'zend_extension=' | sed 's/^;//'")

    # update ini
    if [[ $cmd == 'en' ]]; then
        ini_contents=$(cat << EOF
$zend_extension
[xdebug]
xdebug.remote_enable=1
xdebug.remote_host=$host_ip
xdebug.remote_autostart=$remote_autostart
xdebug.profiler_enable_trigger=1
xdebug.profiler_output_dir=/tmp/webgrind
EOF
)
    else
        ini_contents=$(cat << EOF
;$zend_extension
EOF
    )
    fi
    util::echo info "setting xdebug config on container $php_container to:"
    util::echo info "------"
    echo "$ini_contents"
    util::echo info "------"
    docker-compose exec "$php_container" /bin/bash -c "echo '$ini_contents' > '$ini_path'"
    # restart php-fpm
    util::echo info "restarting php-fpm..."
    docker-compose exec "$php_container" /bin/bash -c 'kill -USR2 1'
}

if [[ ! -z "$cmd" ]]; then
    echo
    main
    echo
fi

cd "$pwd_dir"
